title: <p align="center"> Spandan Garg </p>

logo: "/images/me.PNG?raw=true"

description:
  <p style="align:center;font-size:200%">
  <a href="pdf/SpandanGargResume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/glGarg/">LinkedIn</a> |
  <a href="https://github.com/glGarg">GitHub</a> |
  <a href="https://scholar.google.com/citations?hl=en&user=2cncaXsAAAAJ&view_op=list_works&gmla=AJsN-F65UcHCJWftKNwdL0yVvNLHNQc1F4yl2IiCbN_4bhXPdiqJqON96PPYminw6ju89semeC3Iwl3vXCp79Nj_7ZXNk_kFRj6hXQTD05qAdq1oekQLD9M">Google Scholar</a>
  </p>
  
  <p align="justify">
  I work as a Data & Applied Scientist in the Visual Studio Data Science Team at Microsoft (2020 - Present).
  <br><br>
  Previously, Software Engineering at University of Waterloo (2015 - 2020).
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: G-P06K7CZY43 # Google Analytics tracking ID
