title: <p align="center"> Spandan Garg </p>

logo: "/images/me.PNG?raw=true"

description:
  <p align="center">
  <a href="pdf/SpandanGargResume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/glGarg/">LinkedIn</a> |
  <a href="https://github.com/glGarg">GitHub</a>
  </p>
  
  <p align="justify">
  I am currently a Data & Applied Scientist in Visual Studio Data Science Team @ Microsoft.
  <br><br>
  Previously, Software Engineering @ University of Waterloo.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
# google_analytics: UA-145578661-1 # Google Analytics tracking ID
